/**
 * LandingPage Component
 * 
 * The main entry point of the AI Quiz application.
 * Features a beautiful hero section with animated elements and clear call-to-action.
 * Sets the tone for the premium educational gaming experience.
 */

import React from 'react';
import { useNavigate } from 'react-router-dom';

const LandingPage: React.FC = () => {
  const navigate = useNavigate();

  return (
    <div className="min-h-screen flex items-center justify-center p-4">
      <div className="max-w-4xl mx-auto text-center">
        {/* Animated Background Elements */}
        <div className="absolute inset-0 overflow-hidden pointer-events-none">
          <div className="absolute top-20 left-20 w-72 h-72 bg-gradient-to-br from-primary to-primary-glow rounded-full opacity-20 blur-3xl animate-float"></div>
          <div className="absolute bottom-20 right-20 w-96 h-96 bg-gradient-to-br from-accent to-accent-glow rounded-full opacity-20 blur-3xl animate-float" style={{animationDelay: '1.5s'}}></div>
        </div>

        {/* Main Content */}
        <div className="relative z-10">
          {/* Logo/Brand */}
          <div className="mb-8">
            <div className="inline-flex items-center justify-center w-20 h-20 bg-gradient-to-br from-primary to-secondary rounded-2xl mb-4 shadow-lg">
              <span className="text-3xl font-bold text-white">🧠</span>
            </div>
            <h1 className="text-6xl font-bold bg-gradient-to-r from-primary to-secondary bg-clip-text text-transparent mb-2">
              QuizMaster AI
            </h1>
            <p className="text-xl text-text-muted">Learn Smarter, Play Better</p>
          </div>

          {/* Hero Title */}
          <h2 className="text-5xl font-bold text-text mb-6 leading-tight">
            Turn Any Topic Into an
            <span className="bg-gradient-to-r from-primary to-accent bg-clip-text text-transparent"> Interactive Quiz</span>
          </h2>

          {/* Description */}
          <p className="text-xl text-text-muted mb-12 max-w-2xl mx-auto leading-relaxed">
            Our AI creates personalized quizzes on any subject you choose. 
            From software testing to trivia topics - learn through engaging, 
            Kahoot-style gameplay that adapts to your knowledge level.
          </p>

          {/* Feature Cards */}
          <div className="grid md:grid-cols-3 gap-6 mb-12">
            <div className="glass rounded-2xl p-6 animate-fade-in-scale">
              <div className="w-12 h-12 bg-gradient-to-br from-primary to-primary-glow rounded-xl mb-4 mx-auto flex items-center justify-center">
                <span className="text-2xl">🤖</span>
              </div>
              <h3 className="text-lg font-semibold text-text mb-2">AI-Powered</h3>
              <p className="text-text-muted text-sm">Smart questions generated by advanced AI</p>
            </div>

            <div className="glass rounded-2xl p-6 animate-fade-in-scale" style={{animationDelay: '0.2s'}}>
              <div className="w-12 h-12 bg-gradient-to-br from-accent to-accent-glow rounded-xl mb-4 mx-auto flex items-center justify-center">
                <span className="text-2xl">🎯</span>
              </div>
              <h3 className="text-lg font-semibold text-text mb-2">Any Topic</h3>
              <p className="text-text-muted text-sm">From coding to cooking - we've got you covered</p>
            </div>

            <div className="glass rounded-2xl p-6 animate-fade-in-scale" style={{animationDelay: '0.4s'}}>
              <div className="w-12 h-12 bg-gradient-to-br from-secondary to-primary rounded-xl mb-4 mx-auto flex items-center justify-center">
                <span className="text-2xl">⚡</span>
              </div>
              <h3 className="text-lg font-semibold text-text mb-2">Kahoot Style</h3>
              <p className="text-text-muted text-sm">Fun, fast-paced learning experience</p>
            </div>
          </div>

          {/* CTA Button */}
          <button
            onClick={() => navigate('/topic')}
            className="group relative inline-flex items-center justify-center px-8 py-4 bg-gradient-to-r from-primary to-secondary text-white font-semibold rounded-2xl shadow-lg hover:shadow-xl transform hover:-translate-y-1 transition-all duration-300"
          >
            <span className="mr-3">Start Your Quiz Journey</span>
            <span className="group-hover:translate-x-1 transition-transform duration-300">→</span>
            
            {/* Button Glow Effect */}
            <div className="absolute inset-0 bg-gradient-to-r from-primary to-secondary rounded-2xl opacity-0 group-hover:opacity-20 blur-xl transition-opacity duration-300"></div>
          </button>

          {/* Stats */}
          <div className="flex justify-center gap-8 mt-12 text-center">
            <div>
              <div className="text-2xl font-bold text-primary">10K+</div>
              <div className="text-sm text-text-muted">Quizzes Played</div>
            </div>
            <div>
              <div className="text-2xl font-bold text-accent">500+</div>
              <div className="text-sm text-text-muted">Topics Covered</div>
            </div>
            <div>
              <div className="text-2xl font-bold text-secondary">95%</div>
              <div className="text-sm text-text-muted">Satisfaction Rate</div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default LandingPage;